version: "3.8"
services:
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app

  react-app:
    image: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - api-server
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge